name: dainty_audio
description: A Dart FFI binding to miniaudio
version: 0.0.1
homepage: https://github.com/maks/dainty_audio

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  ffi: ^2.0.1


dev_dependencies:
  ffigen: ^7.2.9
  pedantic: ^1.9.0

ffigen:
  name: "libminiaudio"
  output: "lib/src/libminiaudio_generated_bindings.dart"
  headers:
    entry-points:
      - "native/miniaudio.h"
  llvm-path:
    - "/usr/lib/llvm-13"
  structs:
    rename:
      "_(.*)": "$1_"
    member-rename:
      ".*":
        "_(.*)": "$1_"